### ISSUE TITLE
cuckoo agent as service doesn't work

### ISSUE THREAD

**Issue by valeita** [ctxis/CAPE#274]
Hi,
i have a problem about Cuckoo Sandbox and i hope that you can help me.
I have installed the agent.py of Cuckoo as a Windows Service in the VM Guest Windows 7 64bit, and i started it. To do this, i created a Python class that extend win32serviceutil.ServiceFramework and i inserted the entry point of my agent (app.run()) in the main function of this. Then, Python service_name install, and then start from services of Windows. This is the link that helped me to do this:  https://github.com/top2topii/FlaskServiceWin32/blob/master/win32_service.py.
The Windows service is working, because i did these proves:
in the VM Guest, i request in my web browser for http:/127.0.0.1:8000 and the Flask App Respond to me. So the socket is open. From my physical host machine to VM Guest, i did a curl and a telnet for the <ip_of_vm>:<port_of_flask_agent> (192.168.56.122:8000) and the the agent respond to me the same content. The problem is that when i submit a file in Cuckoo, It doesn't reach my VM during the analysis phase. Do you have some idea about it? Do you know about where i can search for resolving my problem in Cuckoo files and configurations?

**Comment by doomedraven** [comment]
did you took snapshot in running state ?

**Comment by valeita** [comment]
thanks in advance for the response, 
Yes, i took the snapshot in running state. Infact i tried to restore snapshot and reboot the machine to be sure it worked, and the Windows service was started.
i attached the code that i installed as a Windows Service, if can be useful.
[agent.txt](https://github.com/ctxis/CAPE/files/2846282/agent.txt)

**Comment by doomedraven** [comment]
i will check it in 8-10h

**Comment by doomedraven** [comment]
dude you can't use v2 agent in cape, and you open issues in 2 repos, stay with project which you using, agent 0.8 isn't compatible with CAPE

**Comment by kevoreilly** [comment]
I'm not sure if I understand the motivation behind running the agent as a service. What does it achieve? If it ain't broke, don't fix it I would think.

**Comment by valeita** [comment]
i'm working for both project, so the double issue opened (sorry, i wrong to post the agent's version). For both, i want to install the agent as a Windows Service to fight the evasion tecniques of some malware. I want to work on The Windows service because i want to do it unkillable from a malware.

**Comment by doomedraven** [comment]
which malware do that? any hash?

**Comment by valeita** [comment]
https://cape.contextis.com/analysis/26673/
Some malware use API like "TerminateProcess" or other, to kill Windows process. I want to fight this behaviour installing the agent as a Windows Service.

**Comment by doomedraven** [comment]
sorry or i miss something or idk, that is __ursnif__, __and that is totally normal behavior__, that nothing to have to see how you run cuckoo agent, so you just overcomplicate stuff, if you don't want process to be able to kill itself/other, modify that hook OR __verify in config to set to off, to not terminate processes at the end__

**Comment by doomedraven** [comment]
cuckoo.conf
```
# When the timeout of an analysis is hit, the VM is just killed by default.
# For some long-running setups it might be interesting to terminate the
# moinitored processes before killing the VM so that connections are closed.
terminate_processes = off
```

**Comment by valeita** [comment]
mmm no, we did not understand each other. I can do an other example: a malware can list the active processes running on the guest OS system, and kill all process which its name contains "*agent*". If this success, the malware crash the flask app on the system and my sandbox fails the analysis. The question is: How i protect my agent process on the VM Guest? i can develop a rootkit, or i can install my agent as a windows service and play with it to be unkillable.

**Comment by doomedraven** [comment]
man your problem is what you speaking here about cuckoo v2 aka official, cape is hardened against this shit. so or focus on one and learn it in detail, or get sometime and learn differences between them 2 ;)

**Comment by kevoreilly** [comment]
There is nothing inherent in a service process that prevents it from being terminated with the TerminateProcess API. Typically if a service process cannot be terminated it is due to an insufficient token most likely because of the privileged user account the service is running under. But if you launch the agent as a service with a privileged account, then since the agent (and analyzer) uses the CreateProcess API to launch the loader, which in turn uses the same API to launch the malware process, they will end up running with the same account and privileges. Thus this won't help prevent the malware process from being able to terminate the service.

Another point to make is that the agent doesn't run under a process name with the string 'agent' in it. It is a Python process, which doesn't change its name depending on the script it is running.

Of course the malware could enumerate processes and change its behaviour due to the presence of python processes. But if malware decides it's detected something it doesn't like, then the least of our problems is that it might kill the agent. For it just to behave differently and not execute its actual payload is the real issue - whether it noisily kills processes or quietly does very little the resulting analysis is still equally as useless. Noisy killing of processes only helps us find out what triggered the divergence in behaviour.

So if anything I would say that the agent's dependence on Python is its weakness. I would of course be interested in malware that does look for this. In any case of malware detecting the sandbox, examples are really helpful in pinning down exactly what is detected and informing any efforts to further harden against this.

**Comment by doomedraven** [comment]
don't forget you already hide them ;) https://github.com/ctxis/CAPE/blob/c3c35dc763b6b7a49cc36296fdc7d01496c67f64/analyzer/windows/analyzer.py#L955

is what i mentioned with hardening ;)

**Comment by kevoreilly** [comment]
Very true, good point. Hence I think it's better to start with a real example than theory.

**Comment by doomedraven** [comment]
So you need that for upstream cuckoo not cape

**Comment by valeita** [comment]
ok, thanks for all guys, i will follow your advices.
