### ISSUE TITLE
Cannot submit dropped files

### ISSUE THREAD

**Issue by bartblaze** [ctxis/CAPE#280]
When trying to submit a dropped file using the "Submit file" button, and clicking through, CAPE returns:

`Server Error (500)`

To reproduce:
1. Visit this Emotet analysis for example [#37271](https://cape.contextis.com/analysis/37271/)
2. Dropped files tab > Submit file
3. Analyze

**Comment by kevoreilly** [comment]
Thanks Bart, unfortunately this is one of many issues with the public instance that I am aware of, but unfortunately have struggled to get fixed as I do not administrate this server. I will try and push for it to be fixed but am not optimistic.

On the upside this issue is not a fault with the actual code in CAPE so other instances should not suffer with it.

**Comment by kevoreilly** [comment]
Thanks Bart, this is an issue with the community instance that I am aware of which affects all the resubmission buttons. I will try and get it fixed, I appreciate you letting me know.

On the upside this issue is not a fault with the actual code in CAPE so other instances should not suffer with it.

**Comment by doomedraven** [comment]
yep it not affects cape code in github

**Comment by bartblaze** [comment]
Thanks folks! :smiley:
