### ISSUE TITLE
Benignpdf causes high malscore

### ISSUE THREAD

**Issue by seanthegeek** [ctxis/CAPE#385]
Example https://cape.contextis.com/analysis/87902/

**Comment by doomedraven** [comment]
Thats bcz adobe reader does a lot of stuff which looks very suspicious

**Comment by kevoreilly** [comment]
Yeah not sure what can be done about this.

**Comment by kevoreilly** [comment]
I'm planning on closing this soon as it seems to boil down to the fact that Adobe reader does behave in ways that can be fairly described as suspicious.

Another thing to mention is that malscore is a feature inherited from spender-sandbox. I personally don't pay much attention to it as cape has its own classification mechanism which I believe is far superior. I've kept it only because some apparently find it useful.
