### ISSUE TITLE
Decompress VT results in expanded view

### ISSUE THREAD

**Issue by enzok** [ctxis/CAPE#8]
web/analysis/views.py requires the VT results to be decompressed for the antivirus function

**Comment by marirs** [comment]
Hi,

Can you edit the "CAPE/modules/reporting/mongodb.py"
And goto
Line# 264 (it will look like the below) You can delete the following lines. Kevin is fixing that in the next push :)

	# Compress virustotal results
	if "virustotal" in report:
		compressed_vt = zlib.compress(JSONEncoder().encode(report["virustotal"]).encode('utf8'))
        report["virustotal"] = Binary(compressed_vt)

**Comment by enzok** [comment]
That code will be removed in the next push? Or, the fix will be made for that code to work? 

I already added the decompress code to my fork. Just wanted to let him know that the code was missing.

**Comment by marirs** [comment]
Unfortunately, that code will be removed in the next push... Not decompressing the VT results. this bug was noticed, only after pushing it to main branch. Sorry about that, I take responsibility for not checking it thoroughly.
the upcoming code will only compress the cape & behavior (summary & enhanced) results. and will get decompressed back in the view. That is backward compatible too. I did this to handle the 16MB limit of mongodb.

**Comment by enzok** [comment]
OK thanks.
